services:
  app:
    image: ${BACKEND_IMAGE}
    container_name: gifgloo-backend
    network_mode: host
    env_file:
      - .env
    environment:
      APP_LOG_FILE: /var/log/gifgloo/app.log
    volumes:
      - /var/log/gifgloo:/var/log/gifgloo
    restart: unless-stopped
