# Include this once inside the nginx http block.

limit_req_zone $binary_remote_addr zone=toss_callback_per_ip:10m rate=2r/s;

map $request_method $composition_create_limit_key {
    default "";
    POST $binary_remote_addr;
}

limit_req_zone $composition_create_limit_key zone=composition_create_per_ip:10m rate=6r/m;
