from typing import Protocol
from datetime import datetime
from composition.domain.entities.completion_notification import CompletionNotification


class CompletionNotificationRepository(Protocol):
    async def register(self, notification: CompletionNotification) -> str: ...
    async def claim_ready(self, now: datetime) -> CompletionNotification | None: ...
    async def settle(self, notification: CompletionNotification) -> None: ...
    async def cancel(self, job_id: str, user_id: str, endpoint_hash: str) -> None: ...
    async def clean_expired(self, now: datetime) -> None: ...
