from enum import Enum


class AssetCategory(Enum):
    KLIPY_GIF = "KLIPY_GIF"
    USER_UPLOAD = "USER_UPLOAD"
    COMPOSITION_DRAFT = "COMPOSITION_DRAFT"
    COMPOSITION_RESULT = "COMPOSITION_RESULT"
