from enum import Enum


class CompositionStage(Enum):
    EXTRACTING_FRAMES = "EXTRACTING_FRAMES"
    ANALYZING = "ANALYZING"
    GENERATING_DRAFT = "GENERATING_DRAFT"
    COMPOSITING = "COMPOSITING"
    BUILDING_GIF = "BUILDING_GIF"
